kind: ImageStream
apiVersion: image.openshift.io/v1
metadata:
  name: trustify-xtask
  labels:
    app.kubernetes.io/component: create-dump
    app.kubernetes.io/name: trustify-dumps-create-dump
    app.kubernetes.io/part-of: trustify-dumps
spec:
  lookupPolicy:
    local: true
